locks:
-
  name    : pause
  topic   : pause_navigation
  timeout : 0.0
  # Same priority as joystick control, so it'll not block it.
  priority: 100
-
  name    : talker1 
  topic   : talker1
  timeout : 0.0
  priority: 100
