locks:
-
  name    : pauselock
  topic   : pause_navigation
  timeout : 0.0
  # Same priority as joystick control, so it'll not block it.
  priority: 100
-
  name    : talker1lock
  topic   : talker1lock
  timeout : 0.0
  priority: 100
